windows: Support GCE
projectcalico/calico pull request #4176
Opened 2020-11-15 02:48 UTC by lmm

## Description

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2020-11-15 13:54 UTC, song-jiang requested changes
One typo

2020-11-15 13:54 UTC, song-jiang commented on scripts/install-calico-windows.ps1
> +        return ("ec2")
```suggestion
        return ("gce")
```

2020-11-15 23:25 UTC, lmm commented on scripts/install-calico-windows.ps1
> +        return ("ec2")
sigh. thanks for catching that

2020-11-16 17:44 UTC, song-jiang approved these changes
LGTM

2020-11-16 20:04 UTC, merged