[WIP] Added Calico for Windows on AKS
projectcalico/calico pull request #4424
Opened 2021-02-25 18:20 UTC by song-jiang

## Description

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2021-02-25 19:31 UTC, bmckercher123 commented on windows-calico/limitations.md
>  |             | ebpf (Linux-based feature)                                   |
I believe the table has another error per our PR for EE. So not supported should say: Overlay mode with BGP peering. 

@song-jiang 
"Non-overlay mode with BGP peering. That is what we supported. We don't support Overlay mode with BGP peering."

2021-02-25 19:31 UTC, bmckercher123 commented on windows-calico/quickstart.md
> +    - {{site.prodnameWindows}} can only be enabled on newly created clusters.
newly-created

2021-02-25 19:39 UTC, bmckercher123 commented on windows-calico/quickstart.md
> +   Move to next step if you see the same output from above command.
Move to next step if the output from above command matches the following output.

2021-02-25 19:40 UTC, bmckercher123 commented on windows-calico/quickstart.md
> +
Create the AKS cluster with these settings: `network-plugin` to`azure`, and `network-policy` to `calico`.

2021-02-25 19:42 UTC, bmckercher123 commented on windows-calico/quickstart.md
> +    - Only support Kubernetes version 1.20+
- Kubernetes version 1.20+

2021-02-25 19:42 UTC, bmckercher123 approved these changes
Minor changes.

2021-02-25 20:01 UTC, lmm requested changes

2021-02-25 20:01 UTC, lmm commented on windows-calico/quickstart.md
> +1. Add Windows node pool. For example,
Add a Windows node pool

2021-02-25 20:02 UTC, lmm commented
Looking good so far, I added some minor comments. I guess while this could technically support Calico v3.17, in v3.17 we don't support k8s 1.20

2021-02-26 17:53 UTC, song-jiang commented on windows-calico/quickstart.md
> +    --windows-admin-username azureuser \
Normally it is azureuser. It is in MSFT doc.

2021-02-26 18:24 UTC, lmm approved these changes

2021-02-26 18:25 UTC, merged