Deployment changes to support Ubuntu Focal (20.04)
projectcalico/calico pull request #4814
Opened 2021-08-06 06:12 UTC by aptdamia

## Description

1. The previous Bird PPA repository doesn't contain a version of Bird beyond 19.04. Instead, the package from the official repository is compatible with later versions:
https://launchpad.net/ubuntu/focal/+source/bird
2. The previous strategy was using an archived Github repository for etcd3-gateway. The maintained package is available in its official OpenStack repository.

2021-08-06 06:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/projectcalico/calico?pullRequest=4814) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/projectcalico/calico?pullRequest=4814) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/projectcalico/calico?pullRequest=4814) it.</sub>

2021-10-11 10:16 UTC, neiljerram requested changes

2021-10-11 10:16 UTC, neiljerram commented on getting-started/openstack/installation/ubuntu.md
> +
I'm happy with the logic of this change for Focal, but I think we should keep the text - for now - for people installing on Ubuntu older than Focal.  Can you keep the text but add a condition saying that the PPA is only needed for Ubuntu before Focal?

2021-10-11 10:16 UTC, neiljerram commented on getting-started/openstack/installation/ubuntu.md
> +    pip3 install git+https://opendev.org/openstack/etcd3gw.git@dc9f55975ecd5b291eb1014b9fe8393dcd6d7e5c
Is there a strong reason to make this change?  The github.com/dims link still works, and our own internal testing uses it, so I'd prefer to keep it unless these is a strong reason to change.

2021-12-15 21:34 UTC, caseydavenport commented
@aptdamia @neiljerram I believe this PR will need to be rebased on the latest monorepo work in this repository, so I'm going to close this for now.

2021-12-15 21:34 UTC, closed without merging