Misc typo fixes in calicoctl dir
projectcalico/calico pull request #5274
Opened 2021-12-16 04:07 UTC by Akasurde

## Description

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2021-12-16 11:26 UTC, neiljerram requested changes
Just one correction, I think.

2021-12-16 11:26 UTC, neiljerram commented on pod2daemon/flexvol/flexvoldriver.go
> +		return fmt.Errorf("invalid path to umount")
Looks like this one should be "unmount" ?

2021-12-16 11:33 UTC, neiljerram approved these changes

2021-12-16 11:33 UTC, neiljerram commented
/sem-approve

2021-12-16 22:28 UTC, merged

2021-12-17 03:09 UTC, Akasurde commented
@neiljerram @caseydavenport Thanks for the review and merge.