Stop copying CRDs from libcalico-go
projectcalico/calico pull request #5583
Opened 2022-02-07 23:15 UTC by caseydavenport

## Description

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2022-02-07 23:22 UTC, robbrockbank commented on kube-controllers/Makefile
> +		CRDS=$(CURDIR)/../libcalico-go/tests/crds \
tests/crds -> config/crd   ?

2022-02-07 23:25 UTC, caseydavenport commented on kube-controllers/Makefile
> +		CRDS=$(CURDIR)/../libcalico-go/tests/crds \
yep!

2022-02-08 04:05 UTC, robbrockbank approved these changes
I think it's fine, but naively I'm more on the side of generating the yaml directly in the docs site, or having a top level manifests folder.

2022-02-08 04:06 UTC, robbrockbank requested changes
Looks lie a bunch of tests are failing.

2022-02-08 09:45 UTC, electricjesus reviewed
a few things observed from the CI

2022-02-08 09:45 UTC, electricjesus commented on apiserver/Makefile
> +		apply -f /go/src/github.com/projectcalico/calico/libcalico-go/config/crd/
this doesn't seem to pick up the correct path, seems like `:231` needs to change from the current `-v  $(CURDIR):/manifests`

2022-02-08 09:45 UTC, electricjesus commented on apiserver/Makefile
>  		-v $(CURDIR)/test/certs:/home/user/certs \
I can't add a suggestion directly but it seems like you might need to modify the manifests volume above this line to: 
```suggestion
                -v $(CURDIR)/../:/go/src/github.com/projectcalico/calico:rw
		-v $(CURDIR)/test/certs:/home/user/certs \
```

2022-02-09 16:59 UTC, merged