Add DeviceRouteSourceAddress support for v6
projectcalico/calico pull request #5728
Opened 2022-03-09 11:45 UTC by hanamantagoudvk

https://github.com/projectcalico/calico/issues/5179

2022-03-09 13:45 UTC, fasaxc requested changes

2022-03-09 13:45 UTC, fasaxc commented on api/pkg/apis/projectcalico/v3/felixconfig.go
> +	DeviceRouteV4SourceAddress string `json:"deviceRouteV4SourceAddress,omitempty"`
Unfortunately, you can't just change the name of a field here.  It's part of our public API.  Think the best option is to leave the old name as-is and add the new one with an `IPv6` suffix.  Alternatively, you could adjust the syntax of the field to allow for `"<IPv4 address>[,<IPv6 address>]"`  Neither option is great!

2022-03-09 13:45 UTC, fasaxc commented on felix/config/config_params.go
> +	DeviceRouteV4SourceAddress         net.IP            `config:"ipv4;"`
Same here, part of our public API

2022-03-14 06:02 UTC, hanamantagoudvk commented
@fasaxc : please review further... I have addressed your comments.

2022-03-22 17:42 UTC, fasaxc requested changes
Yes, that looks like the right shape now.  I think two more changes are needed:
* Please update the docs.  calico/reference/felix/configuration.md and calico/reference/resources/felixconfig.md
* I think you need to update `numBaseFelixConfigs` in `configurationprocessor_test.go`.

2022-03-22 17:42 UTC, fasaxc commented on felix/config/param_types.go
> +	res := net.ParseIP(raw)
This should really check that it's actually an IPv6 address (and Ipv4Param should check that it's really IPv4!)  Please can you add that.

2022-03-22 17:43 UTC, fasaxc commented
/sem-approve

2022-03-23 16:09 UTC, fasaxc commented
CI failed, you also need to run `make generate` and check in the generated files.

2022-03-24 09:13 UTC, hanamantagoudvk commented
> CI failed, you also need to run `make generate` and check in the generated files.

@fasaxc : I have already `api/pkg/openapi/openapi_generated.go` . In which folder , do i need to execute `make generate` ?

2022-03-28 06:02 UTC, hanamantagoudvk commented
@fasaxc : Hi Shaun, please let me know if you have any more comments.

2022-03-29 16:55 UTC, fasaxc commented
/sem-approve

2022-03-29 17:02 UTC, fasaxc requested changes
Code is looking good, now please can you add unit tests for the parameter validation.

It's also be good to have an FV test for the feature but I don't think the FV harness supports IPv6 yet so that's too big an ask.

2022-03-29 17:02 UTC, fasaxc commented on libcalico-go/lib/validator/v3/validator.go
> +	if c.DeviceRouteSourceAddressIPv6 != "" {
Please add a test for this in the accompanying `_test.go`

2022-04-04 09:40 UTC, fasaxc commented
/sem-approve

2022-04-05 17:25 UTC, fasaxc commented
/sem-approve

2022-04-06 10:04 UTC, hanamantagoudvk commented
@fasaxc : I have fixed the CI issues. Need your approval.

2022-04-07 05:41 UTC, hanamantagoudvk commented
@fasaxc @caseydavenport : Looks like there are random failures. Initially `UT/FV tests on new kernel` failed , but after re-run `kube-controller` tests are failing.

2022-04-07 14:45 UTC, fasaxc commented
Agreed, looks like a flake, but it's not one I've seen before.  Doing a rerun.

2022-04-07 14:46 UTC, fasaxc commented
/merge-when-ready

2022-04-07 14:47 UTC, marvin-tigera commented
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

2022-04-07 16:15 UTC, merged