[RFC] Check active policy only for policy resolver
projectcalico/calico pull request #5835
Opened 2022-04-01 19:53 UTC by yunhjiang

Currently the policy resolver put all the policies into the policySorter
and scan it when a policy becomes matched or mismatched.

However, we need only put the active policy into the policy sorter and
when a policy match change happens, we don't need scan all the policies,
but only the active one. This should reduce a lot of effort.

A new field is added to keep all the policies.

## Description

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2022-05-09 20:38 UTC, caseydavenport commented
/sem-approve

2022-05-09 20:48 UTC, caseydavenport reviewed
@fasaxc is the expert on this bit of code, but I think conceptually this seems sound based on my understanding. 

Essentially:
- Instead of sorting every policy, we just store them until they become active on a node.
- Then, we only sort the active policies for local endpoints, potentially cutting down the complexity of the calculation.

Equivalent to moving the filtering logic out of `sendEndpointUpdate` and executing it prior to the sorting operation. 

I suppose this won't have much of a change on small clusters (where policies are more likely to be applied to a node, and there are fewer policies cluster wide) and it will have a slight occupancy increase in order to get the CPU gains.

2022-05-10 02:27 UTC, yunhjiang commented on felix/calc/policy_sorter.go
> +func (poc *PolicySorter) UpdatePolicy(key model.PolicyKey, newPolicy *model.Policy) (dirty bool) {
Will work as suggestion.

2022-05-10 09:32 UTC, fasaxc requested changes
Change looks like a good improvement, thanks!

2022-05-10 09:32 UTC, fasaxc commented on felix/calc/policy_resolver.go
> +	if _, ok := pr.policySorter.tier.Policies[policyKey]; !ok {
Suggest adding a method to `policySorter` to do this check: `if !policySorter.HasPolicy(policyKey) {` for example

2022-05-10 09:32 UTC, fasaxc commented on felix/calc/policy_resolver.go
> +	// This policy is in active anymore, remove it from the tier also
```suggestion
	// This policy is not active any more, we no longer need to track it for sorting.
```

2022-05-13 16:59 UTC, yunhjiang commented
Thanks for the review. Will update the patch and submit a new version.

2022-08-09 16:40 UTC, caseydavenport commented
@yunhjiang is this something you're still interested in working on?

2023-03-07 17:20 UTC, Josh-Tigera commented
Closing since this has been committed under https://github.com/projectcalico/calico/pull/7336

2023-03-07 17:20 UTC, closed without merging