Adding HTTP /terminate path to Dikastes for graceful termination
projectcalico/calico pull request #6268
Opened 2022-06-23 19:39 UTC by Josh-Tigera

## Description
Introduces an HTTP path "/terminate" for graceful termination of Dikastes to allow for successful completion of Kubernetes jobs. Envoy has an analogous /quitquitquit path so this Dikastes equivalent should be familiar with anyone who has used Envoy outside of Calico

Tested via newly introduced unit tests as well as by manually creating a Job that includes a POST operation via curl to shutdown both Dikastes and Envoy and observing that the Job is successfully marked as completed.

## Related issues/PRs
fixes [5227](https://github.com/projectcalico/calico/issues/5227)

## Todos

- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
Add HTTP /terminate endpoint for graceful termination of Dikastes sidecar container to facilitate Kubernetes Job completion
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2022-06-23 21:02 UTC, caseydavenport requested changes

2022-06-23 21:02 UTC, caseydavenport commented on calico/reference/architecture/overview.md
> +> **Note**: Dikastes can be terminated by issuing an HTTP POST request to /terminate on localhost at the HTTP port specified with the --http-port option when starting Dikastes (default 7777). This is
We usually put CLI options surrounded by backticks I think, so `--http-port`

2022-07-06 17:58 UTC, caseydavenport reviewed
Couple of minor comments but looking good.

2022-07-06 20:13 UTC, caseydavenport commented on app-policy/cmd/dikastes/dikastes.go
> +	httpServerPortStr := fmt.Sprintf(":%s", httpServerPort)
Yep, if you don't specify an address it will bind to all available addresses

2022-07-07 21:00 UTC, merged

2022-07-28 11:54 UTC, brentmjohnson commented
Any interest in releasing this one into the v3.23?  Ran into some scenarios where this would be really valuable (for 3rd party operator managed job manifests).

2022-08-12 14:05 UTC, Josh-Tigera commented
Hi @brentmjohnson,

We don't typically port new content back into older releases, we restrict that to bug fixes only so if this functionality is of use to you please consider upgrading once v3.24 has been released.