Fix L3RouteResolver "some nodes share IP address" log messages
projectcalico/calico pull request #6298
Opened 2022-06-29 23:09 UTC by coutinhop

## Description

Don't export empty (uninitialized) IP addresses in L3RouteResolver, to fix incorrectly outputting "Some nodes share IP address, route calculation may choose wrong node." log messages for those IPs (e.g.: '::/128' when IPv6 is disabled).

ref: https://calicousers.slack.com/archives/CPTH1KS00/p1654705701097149

## Related issues/PRs

## Todos

- [x] Tests
- [ ] Documentation
- [x] Release note

## Release Note

```release-note
Fix L3RouteResolver incorrectly outputting "Some nodes share IP address, route calculation may choose wrong node." log messages.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2022-06-30 09:30 UTC, fasaxc requested changes
LGTM, but it'd be good to have a UT to catch regression of the other issue you fixed.

2022-06-30 15:57 UTC, coutinhop commented on felix/calc/l3_route_resolver.go
> +			c.visitAllRoutes(c.trie.v6T, func(r nodenameRoute) {
Good point, will do! Thanks!

2022-06-30 18:09 UTC, coutinhop commented on felix/calc/l3_route_resolver.go
> +			c.visitAllRoutes(c.trie.v6T, func(r nodenameRoute) {
@fasaxc I did add the UT, and also changed product code to use `trieForCIDR()` which I think will be better. LMK if it looks good. Thanks!

2022-07-06 17:29 UTC, caseydavenport approved these changes

2022-07-07 12:06 UTC, fasaxc approved these changes

2022-07-08 23:05 UTC, merged