Set seccomp profile to RuntimeDefault for calico-kube-controllers and calico-typha
projectcalico/calico pull request #6524
Opened 2022-08-10 09:03 UTC by dimityrmirchev

## Description
We can enhance the `securityContext` of `calico-node`, `calico-kube-controllers`, `calico-typha` by explicitly adding a "RuntimeDefault" seccomp profile.

```yaml
      securityContext:
        seccompProfile:
          type: RuntimeDefault
```
By default Kubernetes runs the pods with profile "Unconfined". Privileged containers always run with `Unconfined` profile ([reference](https://kubernetes.io/docs/tutorials/security/seccomp/#before-you-begin)). Having said that this change will only affect `calico-kube-controllers` and `calico-typha` since all the containers in `calico-node` are ran as privileged. The specifying of the seccomp profile there acts as a guardrails against:
1. Adding a new container and running it as `Unconfined`
2. Removing `privileged: true` from a container definition and still running as `Unconfined`

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
The calico-node, calico-kube-controllers and calico-typha pods now run with `securityContext.seccompProfile.type=RuntimeDefault`.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2022-08-10 09:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/projectcalico/calico?pullRequest=6524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/projectcalico/calico?pullRequest=6524) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/projectcalico/calico?pullRequest=6524) it.</sub>

2022-08-16 14:47 UTC, caseydavenport commented
/sem-approve

2022-08-16 14:48 UTC, caseydavenport commented
@coutinhop could you own reviewing this guy?

2022-12-12 20:51 UTC, dimityrmirchev commented
Friendly ping @caseydavenport @coutinhop

2023-03-14 04:11 UTC, mgleung requested changes
Hey @dimityrmirchev sorry for the delay for the review. I think this would be really good for us to have, but I'm not sure if adding this to all of the node daemonsets would work if they run as privileged. Have you tested these changes?

Also, we generate a lot of the manifests from our [helm charts](https://github.com/projectcalico/calico/tree/master/charts/calico/templates) so a faster change might be to make the changes to those and then re-generate the manifests.

2023-03-14 04:11 UTC, mgleung commented on manifests/calico-bpf.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/calico-etcd.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/calico-policy-only.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/calico-typha.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/calico-vxlan.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/calico.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/canal-etcd.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/canal.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on manifests/flannel-migration/calico.yaml
> +      securityContext:
same as above

2023-03-14 04:11 UTC, mgleung commented on node/tests/k8st/infra/calico-kdd.yaml
> +      securityContext:
same as above

2023-03-27 08:34 UTC, dimityrmirchev commented
Hi @mgleung and thanks for reviewing this PR!

> I think this would be really good for us to have, but I'm not sure if adding this to all of the node daemonsets would work if they run as privileged.

Setting `RuntimeDefault` seccomp profile for `calico-node` will not actually change anything since the containers run as `privileged` (they will still have the `Unconfined` profile). The specifying of the seccomp profile for `calico-node` acts as guardrails against:
 - Adding a new container and running it as `Unconfined`
 - Removing `privileged: true` from a container definition and still running as Unconfined

> Have you tested these changes?

I created a kind cluster with disabled CNI, then applied the regenerated `./manifests/calico.yaml` and `./manifests/calico-typha.yaml`. The calico pods started successfully and I did not observe any errors.

> Also, we generate a lot of the manifests from our [helm charts](https://github.com/projectcalico/calico/tree/master/charts/calico/templates) so a faster change might be to make the changes to those and then re-generate the manifests.

Yes, this is what I did in order to change the files located in the `manifests` folder.

2023-03-27 16:18 UTC, hjiawei commented
Setting `RuntimeDefault` to SeccompProfile should be fine as Tigera Operator had a similar change recently in https://github.com/tigera/operator/pull/2433.

2024-06-18 17:12 UTC, caseydavenport commented
/sem-approve

2024-06-18 22:23 UTC, caseydavenport commented
/sem-approve

2024-06-21 16:34 UTC, merged