bpf no ctlb np
projectcalico/calico pull request #6527
Opened 2022-08-10 18:39 UTC by tomastigera

## Description

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2022-09-06 08:48 UTC, fasaxc requested changes
Few initial questions, made me wonder if I was missing something so thought it best to discuss before I do more digging

2022-09-06 08:48 UTC, fasaxc commented on felix/bpf-gpl/fib.h
> +	/* If we are turnign packets around on lo to a remote pod, approve the
```suggestion
	/* If we are turning packets around on lo to a remote pod, approve the
```

2022-09-06 08:48 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +				__u32 mark = 0;
Why the extra variable?

2022-09-06 08:48 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +	if (rt_addr_is_local_host(ctx->state->ip_src)) {
Should this be limited to program types where the packet is leaving the host?  Don't want the outbound failsafe to kick in on a (spoofed) inbound packet.

2022-09-06 08:48 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +			/* XXX We need to do HEP policy here, where we do NAT. */
Bit confused by setting the `pol_rc = CALI_POL_ALLOW` and then this comment.  But then you fall through to `do_policy`

2022-09-06 08:48 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +			CALI_DEBUG("NP redir on HEP - skip policy\n");
Is this the first program to see this traffic?  I think "wildcard" HEP egress policy should apply from host to local workload even if going via a nodeport.

2022-09-06 08:48 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +		CALI_DEBUG("Host accesses nodeport backend %x:%d\n",
Not sure I follow; looks like there are several codepaths that lead here (via `goto allow`) and not all are nodeports?

2022-09-06 08:48 UTC, fasaxc commented on felix/fv/bpf_test.go
> -							if testOpts.connTimeEnabled {
:tada:

2022-09-06 17:11 UTC, tomastigera commented on felix/bpf/libbpf/libbpf.go
> +	natin, natout uint32,
yeah, it is annoying to add the args :+1:

2022-09-12 14:48 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +	if (rt_addr_is_local_host(ctx->state->ip_src)) {
Ah OK, there's a CALI_F_TO_HEP condition inside this but it doesn't cover the `ctx->state->flags |= CALI_ST_SRC_IS_HOST;` line.

2022-09-12 14:49 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +			CALI_DEBUG("NP redir on HEP - skip policy\n");
I was wrong, wildcard HEPs don't affect host to own pod (and we have FVs that assert that)

2022-09-13 13:41 UTC, fasaxc commented on felix/bpf-gpl/tc.c
> +			/* Did not find a route for a service BE? Should be just
What about out-of-cluster service backends such as the k8s API server?  I don't think they'll have routes

2022-09-13 13:46 UTC, fasaxc requested changes
Spotted a couple of points on second read through.  I'm still wary of accept_local; could we get rid of that if we assume bpf_redirect_neigh?

2022-09-22 17:01 UTC, tomastigera commented
> Spotted a couple of points on second read through. I'm still wary of accept_local; could we get rid of that if we assume bpf_redirect_neigh?

Not sure as if a pod is responding to local host it needs to revers DNAT and the resulting packet may have the local host's source if it was accessing the pod via local nodeport :sweat_smile:  We may be able to deliver straight to a socket but I did not explore that concept yet.

2022-09-28 14:16 UTC, fasaxc approved these changes

2022-09-28 17:14 UTC, merged