Remove `Auto` option for `IptablesBackend`
projectcalico/calico pull request #6871
Opened 2022-10-19 20:18 UTC by huiyizzz

## Description

The value of `IptablesBackend` shoud not be set to auto.
This PR corrects the values of `IptablesBackend` in docs.
## Related issues/PRs

https://github.com/projectcalico/calico/issues/6772
## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2022-10-19 21:41 UTC, caseydavenport requested changes
I'm not sure yet if this is the right fix - we do support auto-detection of the iptables backend in Felix. Certainly the changes to config_params.go seem wrong to me.

I think this might just be a case of the documentation being confusing.

i.e.,

- We support a value of Auto being set as an env var in FELIX_IPTABLESBACKEND
- We do not support a value of Auto being set in the v3 FelixConfiguration API.

This is technically OK since they are different APIs, but our docs imply that the same values are appropriate on both the env var and v3 APIs.

2022-11-08 15:55 UTC, caseydavenport requested changes
I think we're missing a couple of things in this PR:

- Docs updates to this file: https://github.com/projectcalico/calico/blob/master/calico/reference/resources/felixconfig.md
- Unit tests to assert that Auto is accepted through validation, and that Felix config parsing handles it correctly.

I'd look at these two suites:

- https://github.com/projectcalico/calico/blob/master/felix/config/config_params_test.go#L136
- https://github.com/projectcalico/calico/blob/master/libcalico-go/lib/validator/v3/validator_test.go

2022-11-08 15:55 UTC, caseydavenport commented on api/pkg/apis/projectcalico/v3/felixconfig.go
> +	// IptablesBackend specifies which backend of iptables will be used. The default is auto.
This should be "Auto" (capitalized, to match the enum value).

2022-11-18 22:34 UTC, coutinhop commented on libcalico-go/lib/validator/v3/validator_test.go
> +		Entry("should accept a valid IptablesBackend value 'Auto'", api.FelixConfigurationSpec{IptablesBackend: &iptablesBackendAuto}, true),
Could you add cases for accepting "NFT" and "Legacy" and rejecting an invalid value here as well?

2022-11-22 04:53 UTC, mgleung approved these changes

2022-11-22 04:54 UTC, merged