[BPF] avoid calling bpftool and tc to check if things changed
projectcalico/calico pull request #7022
Opened 2022-11-25 01:10 UTC by tomastigera

## Description
    [BPF] avoid calling bpftool and tc to check if things changed
    
    Collect information on all attached programs at the top of
    CompleteDeferredWork and remember that for the duration of it. That is a
    single call to bpftool if there is any change instead of calling and
    parsing it for each modified device.
    
    We also called the bpftool and tc tool multiple times when things
    changed, especially when felix restarted.

    [BPF] xpd AlreadyAttached() calls ProgramID 2x
    
    There is no need for that, if we cannot get program id we know that
    our stuff it not attached and we dont care of something else is
    attached. We need to attach ourselves.

    felix/Makefile: BPF ut test may need roo and cgo

    [BPF] bpf_ep_mgr jumpMapFDs are an array not a map

    [BPF] convert bpf.Hook from string to int
    
    Less need for maps as indexing becomes easy.

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2022-11-30 13:18 UTC, fasaxc requested changes

2022-12-01 00:47 UTC, tomastigera commented on felix/dataplane/linux/bpf_ep_mgr.go
> +	attachedProgs map[bpf.HookDevKey]int
yup, that is where it is being cleared

2022-12-06 21:47 UTC, tomastigera commented on felix/dataplane/linux/bpf_ep_mgr.go
> +				iface.dpState.jumpMapFDs[i] = 0
shouldn't the deep equal match that the array is zeroed?

2022-12-06 21:52 UTC, tomastigera commented on felix/bpf/attach.go
> +		log.WithError(err).Panic("Failed to list attached bpf programs")
sure, I think I went with copy paste, but error it fine

2022-12-07 22:43 UTC, tomastigera commented on felix/bpf/libbpf/libbpf.go
> +func DetachClassifier(ifindex, handle, pref int, ingress bool) error {
but attach is method of object and Query/Detach are functions unrelated to obj, so I placed it in front, but next to it :man_shrugging:

2023-04-11 23:12 UTC, tomastigera commented
Superseded by https://github.com/projectcalico/calico/pull/7219

2023-04-11 23:12 UTC, closed without merging