Fix the auto iptables detection if ip_tables.ko preloaded on RHEL/CentOS 8
projectcalico/calico pull request #7111
Opened 2022-12-20 03:44 UTC by yankay

## Description

The auto iptables detection logic is updated by the Kubernetes [KEP 3178 ](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/3178-iptables-cleanup/README.md),  the 'iptables-wrapper'  can decide which iptables backend to use based on which one kubelet used. 

So that the issue can be fixed by the new 'iptables-wrapper' logic.  The PR is to update it with the new logic:

from:
https://github.com/kubernetes-sigs/iptables-wrappers/blob/v1/iptables-wrapper-installer.sh#L130
to:
https://github.com/kubernetes-sigs/iptables-wrappers/blob/master/iptables-wrapper-installer.sh#L107

## Related issues/PRs

fixes https://github.com/projectcalico/calico/issues/2322
fixes https://github.com/projectcalico/calico/issues/3709

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Fix the auto iptables detection if ip_tables.ko preloaded on RHEL/CentOS 8
```

## Reminder for the reviewer

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.

2022-12-20 05:03 UTC, yankay commented
HI @caseydavenport , @lwr2 , @fasaxc , would you please review it :-)

Thank you very much.

2022-12-22 02:49 UTC, yankay commented
HI @caseydavenport, would you please review the PR , thanks.

2023-01-04 02:48 UTC, yankay commented
HI @tomastigera , would you please review the PR , thank you :-)

2023-01-05 04:58 UTC, cyclinder commented
Hi @caseydavenport @song-jiang , can you please take a look ? Thanks,  I think it's make a sense. 😄

2023-01-12 04:44 UTC, mazdakn commented
@yankay sure, I'll review it in the next few days.

2023-01-12 05:54 UTC, yankay commented
> @yankay sure, I'll review it in the next few days.

Thank you very much

2023-01-12 10:01 UTC, fasaxc commented on felix/environment/feature_detect_test.go
> +			"nft",
I don't think the default should be changing in these tests.  If `iptables-nft` fails to run then I think we should stick with `legacy` mode

2023-01-12 10:03 UTC, fasaxc requested changes
Using the hints seems sensible but I don't think we should change the defaulting behaviour if no hints are detected.  I notice that a bunch of the error tests have been flipped to default to nft now, for example but I'd expect that if `iptbales-nft` fails (presumably because we're on a kernel with no nftables support!) then we should default to legacy mode.

2023-01-16 09:26 UTC, yankay commented
Thank you very much @fasaxc ,
The PR has changed the default from the NTF to the legacy mode.

Would you please review it again :-)

2023-01-31 14:48 UTC, fasaxc commented
/sem-approve

2023-01-31 14:49 UTC, fasaxc approved these changes
LGTM.  Noticed there was a change to a couple of existing tests due to the removal of the 
```
if legacyLines >= 10
```
thanks that's OK now that nft is widely adopted

2023-02-01 02:02 UTC, yankay commented
> LGTM. Noticed there was a change to a couple of existing tests due to the removal of the
> 
> ```
> if legacyLines >= 10
> ```
> 
> thanks that's OK now that nft is widely adopted

Thank you very much for the review :-)

2023-02-02 03:40 UTC, cyclinder commented
Hi @fasaxc , [ci/semaphoreci/pr](https://tigera.semaphoreci.com/workflows/825f7774-3b2d-4308-909b-e4b2acdb60c2/summary?pipeline_id=7db58923-812b-4206-b481-3e4e54f2a1c1) is failling, Does this affect the PR merge?

2023-03-01 22:19 UTC, mgleung commented
/sem-approve

2023-03-08 21:36 UTC, merged

2023-03-09 03:37 UTC, yankay commented
Thanks@mazdakn @fasaxc @mgleung  @cyclinder  for the PR review :-)