Reinstate PATH in calicoctl Dockerfile
projectcalico/calico pull request #8362
Opened 2023-12-20 11:03 UTC by lwr20

## Description

The 3.27 calicoctl image works fine with or without the leading / :
```
$ docker run --rm -ti --entrypoint calicoctl --name calicoctl calico/ctl:v3.27.0 version
Client Version:    v3.27.0
Git commit:        711528eeb
Unable to detect installed Calico version
#

$ docker run --rm -ti --entrypoint calicoctl --name /calicoctl calico/ctl:v3.27.0 version
Client Version:    v3.27.0
Git commit:        711528eeb
Unable to detect installed Calico version
```
But the current master version does not:
```
$ docker run --rm -ti --entrypoint calicoctl --name calicoctl calico/ctl:master version
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "calicoctl": executable file not found in $PATH: unknown.

$ docker run --rm -ti --entrypoint /calicoctl --name calicoctl calico/ctl:master version
Client Version:    v3.28.0-0.dev-250-gf0ea2794de5f
Git commit:        f0ea2794d
Unable to detect installed Calico version
```

This change in behaviour is due to removal of the ENV PATH from the calicoctl Dockerfile in https://github.com/projectcalico/calico/commit/86f77e3a46ce503cbbe47d1123376decedf8e010

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2023-12-20 11:10 UTC, lwr20 commented
Tagging @hjiawei in case there's a good reason for removal of this ENV

2023-12-20 16:22 UTC, hjiawei requested changes
I prefer to copy the binary into a more standardized place like `/usr/bin` for container runtime to find it. With the common `calico/base` change, we are more or less following the stand linux root fs strucutre.

2023-12-20 16:34 UTC, hjiawei commented
One more comment about the above non-working example in the description: the sample command overwrites the entrypoint ships with the container and expect it to work properly. I don't think this is a supported case.

The following command works fine without redefining the entrypoint:

```bash
docker run --rm -ti --name calicoctl calico/ctl:master calicocot -- version
```

2023-12-21 10:26 UTC, lwr20 commented
Closing in favour of #8364

2023-12-21 10:26 UTC, closed without merging