bump ipset protocol version
projectcalico/calico pull request #8387
Opened 2024-01-03 21:16 UTC by mazdakn

## Description
Bump ipset protocol version to 8.

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2024-01-11 18:12 UTC, fasaxc requested changes
Thanks, generally looking good; a few comments inline; mainly on naming/style suggestions.

Is there any sane way that we could write an FV test for this?  How easy is it to get hold of a newer ipset binary to create a "bad" IP set?  Could we do 
```
docker run <some off the shelf image> -net=<felix container> ipset create foo bar
```
perhaps?

2024-01-11 19:59 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +	ipsets, err := s.list(debug)
Done.

2024-01-11 20:20 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +func (s *IPSets) get(ipSetName string, debug bool) ([]string, error) {
Fixed.

2024-01-11 20:23 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +		s.logCxt.Debugf("IP set %v:\n%v", ipSetName, lines)
Fixed.

2024-01-11 22:07 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +		return lines, nil
Fixed.

2024-01-11 22:08 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +		return ipSets, nil
Great, the style looks much better now.

2024-01-11 22:08 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +		return ipSets, nil
Fixed.

2024-01-11 22:12 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +func (s *IPSets) parse(ipSetName string, debug bool) error {
Fixed.

2024-01-11 22:43 UTC, mazdakn commented on felix/ipsets/ipsets.go
> +			lines = append(lines, scanner.Text())
Fixed.

2024-01-11 23:15 UTC, mazdakn commented on felix/ipsets/ipsets_test.go
> +// Copyright (c) 2016-2024 Tigera, Inc. All rights reserved.
Done.

2024-01-12 19:29 UTC, mazdakn commented
@fasaxc adding a test to check this reliably depends on the host's kernel version:
```
[root@felix-0-61811-4-felixfv /]# ipset create test hash:ip bitmask 24
ipset v7.19: Argument `bitmask' is supported in the kernel module of the set type hash:ip starting from the revision 6 and you have installed revision 5 only. Your kernel is behind your ipset utility.
Try `ipset help' for more information.
[root@felix-0-61811-4-felixfv /]# uname -r
5.15.0-91-generic
```

So if we add a test to verify the error and also its fix, it would run differently based on the host. Unless we skip the test based on kernel version. In that case, I prefer to add it in another PR since it would need more work. WDYT?

2024-01-15 09:44 UTC, fasaxc commented on felix/ipsets/utils_for_test.go
> +			SetName:   arg[1], // either ipset name or '-name' to return the list of all ipsets
I'd prefer you to set this to "" if -name is specified.  OK to only handle some cases but watch out for setting fields to misleading values that might get picked up later on.

2024-01-15 09:45 UTC, fasaxc approved these changes
LGTM, thanks for taking my style comments on board; code looks really clean (to me!) now.  Let's not add the extra test; sounds like it's too fiddly to do given the kernel limits.

One nit-level comment but I don't need to see it again.

2024-01-15 19:12 UTC, merged