Update as the older format was deprecated
projectcalico/calico pull request #8693
Opened 2024-04-04 19:11 UTC by debasishbsws

## Description
bfp_map_def  map declaration was deprecated https://github.com/libbpf/libbpf/wiki/Libbpf%3A-the-road-to-v1.0#drop-support-for-legacy-bpf-map-declaration-syntax

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2024-04-04 19:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/projectcalico/calico?pullRequest=8693) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/projectcalico/calico?pullRequest=8693) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/projectcalico/calico?pullRequest=8693) it.</sub>

2024-04-07 23:56 UTC, mazdakn requested changes
@debasishbsws Thanks for finding and fixing this. We recently fixed the issue in PR https://github.com/projectcalico/calico/pull/8610, but failed to catch this one.

2024-04-07 23:56 UTC, mazdakn commented on felix/bpf-apache/sockops.c
> +} calico_sk_endpoints __attribute__((section(".maps")));
@debasishbsws this is correct, but please replace it with `SEC()` macro to align with other files.

2024-04-07 23:58 UTC, mazdakn commented on felix/bpf-apache/sockops.c
> +} calico_sk_endpoints __attribute__((section(".maps")));
Like the one here: https://github.com/projectcalico/calico/blob/5741d7df6dfe2453c41be46f4d990dd7b56b1d4c/felix/bpf-apache/filter.h#L28

2024-04-08 18:06 UTC, mazdakn commented on felix/bpf-apache/sockops.c
> +} calico_sk_endpoints __attribute__((section(".maps")));
@debasishbsws I went ahead, and fixed this. Thanks for reporting this.

2024-04-08 18:06 UTC, mazdakn approved these changes

2024-04-08 20:02 UTC, sridhartigera approved these changes

2024-04-08 20:06 UTC, merged