[BPF] fix forwarding and NATing of ICMP related messages
projectcalico/calico pull request #8858
Opened 2024-05-25 00:57 UTC by tomastigera

When a service (nodeport) is accessed from outside the cluster and traffic from backend generates ICMP error outside the cluster, we need to deliver the ICMP error (e.g. MTU too big) back to the backend workload so that it can adjust. These packets were not sent back into the vxlan tunnel neither we did DNAT on them if they were.

fixes https://github.com/projectcalico/calico/issues/8854

## Description

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2024-06-07 09:41 UTC, fasaxc requested changes
Couple of tiny nits and a question on the mark pattern.  Thanks for all the tests, exactly the sort of function that it's easy to regress without good tests.

2024-06-07 14:42 UTC, sridhartigera commented on felix/fv/bpf_test.go
> +								ipRouteFlushlushCache := []string{"ip", "route", "flush", "cache"}
```ipRouteFlushCache```?

2024-06-07 17:33 UTC, tomastigera commented on felix/bpf-gpl/bpf.h
> +	CALI_SKB_MARK_RELATED_RESOLVED        = 0x11000000,
Noooooooooooooo :man_facepalming: I was sooo happy that I had one bit

2024-06-07 18:08 UTC, tomastigera commented on felix/bpf-gpl/bpf.h
> +	CALI_SKB_MARK_RELATED_RESOLVED        = 0x11000000,
Ohhh there seems to be one more left! :tada:

2024-06-07 20:48 UTC, sridhartigera approved these changes
LGTM

2024-06-10 15:08 UTC, fasaxc commented
CI failing with a timeout in the BPF tests?

2024-06-10 23:22 UTC, tomastigera commented
> CI failing with a timeout in the BPF tests?

That is unfortunate, but unrelated as it predates this patch :-/

2024-06-10 23:22 UTC, tomastigera commented
some unrelated flakes

2024-06-10 23:23 UTC, merged