[BPF] set MTU on bpfin/out.cali to match host
projectcalico/calico pull request #8922
Opened 2024-06-18 00:08 UTC by tomastigera

Set the MTU to match the smallest MTU of the host devices as per the current autodetection. That makes sure that if large MTU is used, the extra device does not create a bottleneck with a small MTU. Also when MTU changes, on host devices, it get adjusted automatically.

Fixes https://github.com/projectcalico/calico/issues/8918

## Description

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2024-06-18 21:29 UTC, tomastigera commented
/merge-when-ready

2024-06-18 21:29 UTC, marvin-tigera commented
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

2024-06-20 08:27 UTC, fasaxc requested changes
Could do with a test, but LGTM otherwise

2024-06-25 06:39 UTC, tomastigera commented
> Could do with a test, but LGTM otherwise

enabled VXLAN mtu tests that now also check the bpf special device mtu which is set to the overlay mtu

2024-06-25 07:13 UTC, tomastigera commented
> Could do with a test, but LGTM otherwise

I enabled the vxlan mtu test for vxlan and it now also tests the bpfin.cali mtu

2024-06-27 14:13 UTC, fasaxc approved these changes
One nit but LGTM

2024-06-27 14:13 UTC, fasaxc commented on felix/dataplane/linux/bpf_ep_mgr.go
> +	hostMTU int,
Called podMTU one later up, maybe bring them into sync or make this `bpfIfaceMTU` so it's more clear what it's for?

2024-06-27 14:51 UTC, tomastigera commented
/merge-when-ready

2024-06-27 14:51 UTC, marvin-tigera commented
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

2024-06-28 08:46 UTC, marvin-tigera commented
Removing "merge-when-ready" label due to new commits

2024-06-28 10:43 UTC, tomastigera commented
The only error has a fix here https://github.com/projectcalico/calico/pull/8952

2024-06-28 10:43 UTC, merged