[BPF] send RST to midflow TCp packets from unknown streams
projectcalico/calico pull request #8933
Opened 2024-06-20 21:31 UTC by tomastigera

## Description

    For a smooth switch from iptables to ebpf mode, we do not want to
    interrupt existing connections. If we see midflow packets, we pass them
    to the host stack. If the stack can verify that they belong to an
    existing conntrack, we let them through and we learn the conntrack.
    
    We drop the rest. However, there are some situations when we can see a
    stray TCP packet during ebpf mode, for instance when a pod dies and ECMP
    kicks in and sends a packet to a different host.
    
    If such a packet gets dropped, the end of the connections remains stuck.
    This change sends an RST to such a stream instead of just dropping the
    packets so that the end host can break the connection.
    
Fixes https://github.com/projectcalico/calico/issues/8882

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
ebpf: don't drop, but reject unknown midflow tcp packets with rst 
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2024-06-25 10:39 UTC, fasaxc requested changes

2024-06-25 10:39 UTC, fasaxc commented on felix/dataplane/linux/int_dataplane.go
> +				Comment: []string{fmt.Sprintf("%s packets from unknown TCP flows.", d.ruleRenderer.IptablesFilterDenyAction())},
```suggestion
				Comment: []string{fmt.Sprintf("%s packets from unknown non-TCP flows.", d.ruleRenderer.IptablesFilterDenyAction())},
```

2024-06-28 13:06 UTC, tomastigera commented
only a single unrelated failure fixed here https://github.com/projectcalico/calico/pull/8952

2024-06-28 13:35 UTC, fasaxc approved these changes

2024-07-02 22:09 UTC, merged