Bug: csidriver crash loop / pod terminating forever
projectcalico/calico pull request #9279
Opened 2024-09-25 10:35 UTC by aaaaaaaalex

## Description

Pods which use nodeagent volumes will stay in Terminating phase forever, if their node reboots while they are in the Terminating phase.

Post-boot, the container is not restored and we don't see its nodeagent files appear in the host FS, since it is meant to be terminating. Kube will then invoke our CSI-driver's TearDown routine. The TearDown routine fails because we cannot find the nodeagent files which we assume are mounted (even though we only want to delete them anyway...).

This PR logs "NotExists" FS errors and continues, rather than logging and exiting, to ensure we don't block the TearDown process.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Fix a bug where pods with flexvol/nodeagent volumes would get stuck in the Terminating phase, if, during termination, their node rebooted.
```
## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2024-09-25 16:02 UTC, fasaxc requested changes
Few minor suggestions, also could do with tests so we don't regress (and to confirm that the real errors actually match the conditions etc).

2024-09-25 16:02 UTC, fasaxc commented on pod2daemon/csidriver/driver/node.go
> +		log.Info("Ignoring ErrNotExist and continuing with unmount")
```suggestion
		log.Info("Pod information file is already gone, continuing with unmount.")
```
Might rephrase to be a little more user accessible.  OK, the user might not know what the pod info file is but the log sortof hints that we were trying to get rid of it.

2024-09-27 10:44 UTC, aaaaaaaalex commented on pod2daemon/csidriver/driver/node.go
> +		if !errors.Is(err, fs.ErrNotExist) {
Did a quick demo and this equivalence check does seem to work.

Looking at the code, there does seem to be aliasing happening.

Our helper functions call the `os` package (`os.Remove` in this case), but errors returned from that function are all of type `PathError`, and the definition of `os.PathError` is:

```
fs.PathError
```

2024-10-01 11:45 UTC, fasaxc approved these changes
LGTM, thanks for making sure test failure actually fails CI the job.  Good catch.

2024-10-01 11:54 UTC, merged