[BPF] Enhance conntrack map flexibility with CPU-based scaling
projectcalico/calico pull request #9581
Opened 2024-12-10 03:36 UTC by ioworker0

## Description

- new feature

Previously, BPFMapSizeConntrack was set to a fixed value, which lacked
flexibility across different spec of machines. Now, with the introduction
of BPFMapSizeConntrackWithCPUFactor, the conntrack map size can be adjusted
based on the number of CPU cores. This allows for larger map sizes on
high-spec machines and smaller map sizes on lower-spec machines, optimizing
resource usage accordingly.

BTW, recently, we added several high-spec machines to the data center, which
led to the conntrack map size being filled up on these machines. It could
have been avoided with BPFMapSizeConntrackWithCPUFactor IHMO.

## Related issues/PRs

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Enhance conntrack map flexibility with CPU-based scaling.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

2024-12-10 03:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/projectcalico/calico?pullRequest=9581) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/projectcalico/calico?pullRequest=9581) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/projectcalico/calico?pullRequest=9581) it.</sub>

2024-12-10 18:25 UTC, tomastigera commented
Might be related to https://calicousers.slack.com/archives/CPEPF833L/p1733131626596509

2024-12-11 10:28 UTC, lwr20 commented
re. the lack of counters, in the thread that Tomas linked, @fasaxc said:
> I think we do have counters on master: https://github.com/projectcalico/calico/blob/master/felix/bpf/conntrack/bpf_scanner.go#L43
> I added them when implementing the new BPF-based conntrack cleaner

2024-12-11 10:41 UTC, lwr20 commented
I have some nervousness about this approach to auto-scaling - it seems that the intent here is to scale the map size based on CPU size.  But map size is about memory, isn't it?  And _free_ memory on a node depends entirely about how tightly you pack workload pods onto the node.  So I'm not entirely sure about the basic premise of this PR.  I'm worried that we create an API that we have to support forever, but isn't a good experience for most users.

> Previously, BPFMapSizeConntrack was set to a fixed value, which lacked
flexibility across different spec of machines.

The "lacking flexibility" part is not entirely true.  The `default` felixconfig applies globally, but it can be overridden for particular nodes by making felixconfigs called `node.<nodename>`.  See https://docs.tigera.io/calico/latest/reference/resources/felixconfig#felixconfig

> Calico automatically creates a resource named default containing the global default configuration settings for Felix. You can use calicoctl to view and edit these settings
> The resources with the name node.<nodename> contain the node-specific overrides, and will be applied to the node <nodename>. When deleting a node the FelixConfiguration resource associated with the node will also be deleted.

Now clearly if you have a lot of large nodes, that's going to be a pain to configure.  ISTR @caseydavenport proposed a system where we add matchlabels to Felixconfigs, and you would then label the nodes so that the correct felixconfig applies to them, and you would only need a felixconfig per node-type in your cluster.  That might solve this issue in a way which works for more users?

2024-12-11 10:51 UTC, ioworker0 commented
> re. the lack of counters, in the thread that Tomas linked, @fasaxc said:
> 
> > I think we do have counters on master: https://github.com/projectcalico/calico/blob/master/felix/bpf/conntrack/bpf_scanner.go#L43
> > I added them when implementing the new BPF-based conntrack cleaner

Ah... I didn't notice them before, and they are really useful as well, thanks!

However, when it comes to troubleshooting issues with the conntrack map, we still need counters for conntrack creation failure events, IHMO ;)

2024-12-11 11:26 UTC, ioworker0 commented
> felixconfig per node-type

Thanks a lot for the points!

As a CNI like Calico, I believe that auto-scaling is appropriate. It might also be better to adjust the map size based on available memory, as you suggested, similar to how network stack parameters such as TCP buffer sizes are dynamically adjusted according to system memory in Linux kernel, IIRC.

Moreover, maintaining Felix configurations for each node-type could be a little challenging; nobody dislikes having less config, I guess. Kubernetes aims to free us from managing individual machines, allowing us to focus less on the specific types of machines within a cluster, IHMO.

what do you think?

2024-12-11 11:27 UTC, ioworker0 commented
> I have some nervousness about this approach to auto-scaling - it seems that the intent here is to scale the map size based on CPU size. But map size is about memory, isn't it? And _free_ memory on a node depends entirely about how tightly you pack workload pods onto the node. So I'm not entirely sure about the basic premise of this PR. I'm worried that we create an API that we have to support forever, but isn't a good experience for most users.
> 
> > Previously, BPFMapSizeConntrack was set to a fixed value, which lacked
> > flexibility across different spec of machines.
> 
> The "lacking flexibility" part is not entirely true. The `default` felixconfig applies globally, but it can be overridden for particular nodes by making felixconfigs called `node.<nodename>`. See https://docs.tigera.io/calico/latest/reference/resources/felixconfig#felixconfig
> 
> > Calico automatically creates a resource named default containing the global default configuration settings for Felix. You can use calicoctl to view and edit these settings
> > The resources with the name node. contain the node-specific overrides, and will be applied to the node . When deleting a node the FelixConfiguration resource associated with the node will also be deleted.
> 
> Now clearly if you have a lot of large nodes, that's going to be a pain to configure. ISTR @caseydavenport proposed a system where we add matchlabels to Felixconfigs, and you would then label the nodes so that the correct felixconfig applies to them, and you would only need a felixconfig per node-type in your cluster. That might solve this issue in a way which works for more users?

Thanks a lot for the points!

As a CNI like Calico, I believe that auto-scaling is appropriate. It might also be better to adjust the map size based on available memory, as you suggested, similar to how network stack parameters such as TCP buffer sizes are dynamically adjusted according to system memory in Linux kernel, IIRC.

Moreover, maintaining Felix configurations for each node-type could be a little challenging; nobody dislikes having less config, I guess. Kubernetes aims to free us from managing individual machines, allowing us to focus less on the specific types of machines within a cluster, IHMO.

what do you think?

2024-12-12 12:45 UTC, ioworker0 commented
@tomastigera 

I'm just wondering if it is possible for you to take a review?

2024-12-30 02:16 UTC, ioworker0 commented
> @tomastigera

@tomastigera PING ~

2025-01-02 14:55 UTC, fasaxc requested changes
I think this is a reasonable incremental improvement on what we have that doesn't do any harm if you don't actively use it.

Ideally, we'd auto-size the conntrack map based on load.  If we see it get full, double its size, but that's a lot more work.

It'd also be nice to have a config model that allows for configuring groups of similar nodes by selector.

2025-01-02 14:55 UTC, fasaxc commented on felix/dataplane/linux/int_dataplane.go
> +		bpfconntrack.SetMapSize(config.BPFMapSizePerCPUConntrack * bpfmaps.NumPossibleCPUs())
Please adjust so that `bpfconntrack.SetMapSize` is only called once after calculating which of the two settings should apply.  Easy to miss this second call when reading the code later.

2025-01-02 14:55 UTC, fasaxc commented on api/pkg/apis/projectcalico/v3/felixconfig.go
> +	// conntrack map can cause disruption.
```suggestion
	// BPFMapSizePerCPUConntrack determines the size of conntrack map based on the number of CPUs. If set to a
	// non-zero value, overrides BPFMapSizeConntrack with `BPFMapSizePerCPUConntrack * (Number of CPUs)`.
	// This map must be large enough to hold an entry for each active connection.  Warning: changing the size of the
	// conntrack map can cause disruption.
```

2025-01-03 01:43 UTC, ioworker0 commented
Thanks a lot for taking time to review!

> I think this is a reasonable incremental improvement on what we have that doesn't do any harm if you don't actively use it.

Yeah, this is a simple/harmless change that effectively solves the issue we're facing ;)

> 
> Ideally, we'd auto-size the conntrack map based on load. If we see it get full, double its size, but that's a lot more work.

Totally agreed. It's actually more like future-proofing work, so let's do it separately ;p

> 
> It'd also be nice to have a config model that allows for configuring groups of similar nodes by selector.

However, IMHO, it might be a bit challenging, as we currently lack a clear way to know how many groups of nodes there are, whether they are faster or slower ;(

2025-01-03 01:44 UTC, ioworker0 commented on api/pkg/apis/projectcalico/v3/felixconfig.go
> +	// conntrack map can cause disruption.
Yep, It would be better.

2025-01-03 01:46 UTC, ioworker0 commented on felix/dataplane/linux/int_dataplane.go
> +		bpfconntrack.SetMapSize(config.BPFMapSizePerCPUConntrack * bpfmaps.NumPossibleCPUs())
Good catch! Will adjust as you suggested ;)

2025-01-03 11:28 UTC, ioworker0 commented
> take a review

@fasaxc everything is ready, could please take a review again?

2025-01-03 11:29 UTC, ioworker0 commented
> Thanks a lot for taking time to review!
> 
> > I think this is a reasonable incremental improvement on what we have that doesn't do any harm if you don't actively use it.
> 
> Yeah, this is a simple/harmless change that effectively solves the issue we're facing ;)
> 
> > Ideally, we'd auto-size the conntrack map based on load. If we see it get full, double its size, but that's a lot more work.
> 
> Totally agreed. It's actually more like future-proofing work, so let's do it separately ;p
> 
> > It'd also be nice to have a config model that allows for configuring groups of similar nodes by selector.
> 
> However, IMHO, it might be a bit challenging, as we currently lack a clear way to know how many groups of nodes there are, whether they are faster or slower ;(

@fasaxc everything is ready, could please take a review again?

2025-01-03 14:33 UTC, fasaxc commented
/sem-approve

2025-01-04 03:51 UTC, ioworker0 commented
/sem-approve

2025-01-04 03:59 UTC, ioworker0 commented
> /sem-approve

Okay, I cannot launch the workflow :(

2025-01-06 11:21 UTC, fasaxc commented
/sem-approve

2025-01-06 13:09 UTC, fasaxc commented
You need to rev the count of expected config params in `configurationprocessor_test.go`.

2025-01-06 13:25 UTC, ioworker0 commented
> You need to rev the count of expected config params in `configurationprocessor_test.go`.

Ah, I see. IIUC, revving that to 153, right?

2025-01-06 13:30 UTC, ioworker0 commented
> Waiting for status to be reported

Done.

2025-01-06 13:31 UTC, ioworker0 commented
> > You need to rev the count of expected config params in `configurationprocessor_test.go`.
> 
> Ah, I see. IIUC, revving that to 153, right?

Done.

2025-01-06 13:43 UTC, fasaxc commented
/sem-approve

2025-01-06 15:16 UTC, ioworker0 commented
What happened when doing 'Tests a /32 LB service with externalTrafficPolicy=Local using a RR'?

It seems that it has nothing to do with this PR :(

[1] https://tigera.semaphoreci.com/jobs/11d060de-4b84-4208-8e29-c435440df9c9#L1208

2025-01-06 16:48 UTC, fasaxc commented
Just a flake, it passed on re-run.

2025-01-06 16:49 UTC, merged

2025-01-06 16:49 UTC, fasaxc commented
Merged, thank you!

2025-01-07 01:38 UTC, ioworker0 commented
> Merged, thank you!

Thanks a lot for your time! It was a wonderful journey ~